# Generated by Django 4.2.18 on 2025-06-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('certificate_pdf', models.FileField(blank=True, null=True, upload_to='certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institute', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_title', models.CharField(max_length=100)),
                ('pro_icon', models.CharField(default='💼', max_length=10)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('pro_image', models.ImageField(upload_to='projects/')),
                ('pro_desc', models.TextField()),
                ('github_link', models.URLField()),
                ('tech_stack', models.CharField(max_length=200)),
            ],
        ),
    ]
