# Generated by Django 4.2.18 on 2025-06-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='certificate_pdf',
        ),
        migrations.AddField(
            model_name='certification',
            name='certificate_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
