# Generated by Django 4.2.18 on 2025-06-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_certification_certificate_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pro_video',
            field=models.FileField(blank=True, null=True, upload_to='project_videos/'),
        ),
    ]
