# Generated by Django 4.2.18 on 2025-06-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_pro_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pro_image',
        ),
    ]
