# Generated by Django 4.2.18 on 2025-06-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_project_pro_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pro_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
