# Generated by Django 4.2.18 on 2025-06-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_pro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pro_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
