# Generated by Django 4.2.18 on 2025-06-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_project_pro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pro_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
