# Generated by Django 4.2.18 on 2025-06-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_project_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pro_icon',
            field=models.CharField(default='fas fa-briefcase', max_length=50),
        ),
    ]
