# Generated by Django 4.2.18 on 2025-08-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_url', models.URLField(blank=True, null=True)),
                ('experience_type', models.CharField(choices=[('internship', 'Internship'), ('job', 'Job')], max_length=10)),
                ('work_mode', models.CharField(choices=[('onsite', 'Onsite'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='onsite', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(help_text='Comma separated technologies', max_length=300)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
